# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PiPi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod ‘RxSwift’, ‘~> 5’
pod ‘RxCocoa’, ‘~> 5’
pod ‘Alamofire’, ‘~> 5.2’
pod 'RxAlamofire'
pod 'Moya', '~> 14.0'
pod ‘SwiftLint’
pod 'ResizingTokenField'
pod 'FSCalendar'
pod 'Kingfisher', '~> 5.0'
pod "TKFormTextField"
pod 'NSObject+Rx'
pod 'iOSDropDown'

  # Pods for PiPi

end
